spring.application.name=careertrack
server.port=${PORT:8080}
# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/careertrack}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}